AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: Z
      Authorizers:
        Z:
          UserPoolArn: !GetAtt U.Arn

Resources:
  U:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CampusSyncUsers
      Policies:
        PasswordPolicy:
          MinimumLength: 8

  C:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref U
        ClientName: CampusSyncApp
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

  StudentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 256
      Timeout: 15
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StudentTable
      Environment:
        Variables:
          TABLE: !Ref StudentTable
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../backend
      DockerTag: v1